version: 2
jobs:
  build:
    working_directory: ~/adblockplussbrowser
    steps:
      - checkout
      - run:
          name: Assemble Debug
          command: ./gradlew assembleDebug 
          environment:
            TERM: dumb
      - run:
          name: Assemble Release
          command: ./gradlew assembleRelease 
          environment:
            TERM: dumb